[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "orgmate"
version = "0.1"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.scripts]
om = "orgmate.main:main"
